# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/
toggle_key: OFF
backend: Auto
# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: "date --rfc-3339=s"
  - trigger: ":uuid"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "uuidgen"    
  - trigger: ":tod"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: "date --rfc-3339=date"
  - trigger: ":mon"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: "date +\"%G-%m\""
  - trigger: ":fac"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: "date +\"%G-%m-facture-\""
  - trigger: ":mfac"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: "date +\"mv ~/Téléchargements/%G-%m-facture-\""
  - trigger: ":wtc"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl -s whatthecommit.com/index.txt"
